org.gradle.jvmargs=-Xmx2048M -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true


systemProp.javax.net.ssl.trustStoreType=jks
systemProp.javax.net.ssl.trustStore=/usr/lib/jvm/java-17-openjdk-amd64/lib/security/cacerts
systemProp.javax.net.ssl.trustStorePassword=changeit

