# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4g
android.useAndroidX=true
android.enableJetifier=true

# Keystore credentials (from ~/.gradle/gradle.properties)
storePassword=${SPARK_STORE_PASSWORD}
keyPassword=${SPARK_KEY_PASSWORD}
keyAlias=${SPARK_KEY_ALIAS}
storeFile=${SPARK_STORE_FILE}
